# -------
# Library
# -------

library:
  name: FeedbackManager
  api: 21
  github: MFlisar/FeedbackManager
  maven: io.github.mflisar.feedbackmanager
  maven-main-library: library
  multiplatform: false
  platforms:
    - android
  screenshots:  []
  branch: master
  demo: false

# ------------
# Dependencies
# ------------

dependencies:
  experimental: false

# ------------
# Groups
# ------------

groups: []

# ------------
# Modules
# ------------

modules:
  - name: library
    group: core
    description: This is a very small library that allows you to send feedback from an app without internet permission via email, either directly or via an unintrusive notification.
    optional: false
    platforms:
      - android
    platforms-info: ""
    dependencies:
      - name: CacheFileProvider
        link: https://github.com/MFlisar/CacheFileProvider
        version: 0.4.0